### PR TITLE
Update React computed to use useMemo

### PR DESCRIPTION
**Pull request by w3cj**
This simple example likely wouldn't require the use of useMemo in the real world, but this is the closest to computed state like the other examples.

### CODE REVIEW

**Comment by matschik** [comment]
Conflicting with https://github.com/matschik/component-party/pull/98

**Comment by omar2205** [comment]
Maybe it needs mentioning. A lot of beginner devs overlook `useMemo`.

**Comment by lookto** [comment]
I agree with @omar2205. 
Most devs, especially juniors, don't even know about useMemo (speaking from my experience ofc). It's the best practise for computed state in React and should at least be mentioned.

**Comment by matschik** [comment]
It's not because beginners overlook `useMemo` that this example needs to use `useMemo`.
In this example, it's pure overhead for a so cheap calculation. Beginners will then misused `useMemo`.
Also a lot of React developers use too much `useMemo`.

If you want a showcase of `useMemo`, it would be better creating an example using an expensive calculation like in React documentation: https://beta.reactjs.org/apis/react/useMemo

**Comment by w3cj** [comment]
Sure. Maybe there should be another section on "complex computed state" or something like that.

Right now the computed examples from Svelte and Vue are not functionally equivalent to the other framework examples. `$:` in Svelte and `computed` in Vue only re-run the double calculation if the dependencies of the calculation have changed. All of the examples for the other frameworks will re-run the double calculation on every render.

This would be the equivalent in Svelte and Vue if we want examples that re-run every render like all the other frameworks:

```vue
<script setup>
import { ref } from 'vue';
const count = ref(10);
</script>

<template>
  <div>{{ count * 2 }}</div>
</template>
```

```svelte
<script>
	let count = 10;
</script>

<div>{count * 2}</div>
```

**Comment by matschik** [comment]
@w3cj You are over-optimizing this snippet for nothing. This snippet is very simple intentionally to showcase how each framework handle computed values. It's not meant to be the super-over-optimized code.
I just added an issue about memoization.

**Comment by w3cj** [comment]
The change I provided was not intended as an optimization, it was intended to provide consistency between examples.

**Pull request closed without merging**
