### PR TITLE
improve svelte data fetching sample code

### PR DESCRIPTION
**Pull request by jinyus**

### CODE REVIEW

**Comment by matschik** [comment]
This updated snippet has less lines but it looks less like other framework implementations.
In Component Party, we prioritize readability to better compare with other frameworks.

**Comment by jinyus** [comment]
This was a one-to-one port of the [SolidJS version](https://github.com/matschik/component-party/blob/main/content/7-webapp-features/2-fetch-data/solid/App.jsx) and it is the recommended way to handle promises it svelte. Should I update the solid version to look like other frameworks as well?

PS: Why would it be better to avoid svelte constructs to force it to look like other frameworks? The await block was made so you don't have to handle the state changes of a promise manually...which is error prone.

**Comment by matschik** [comment]
SolidJS `createResource` & Svelte `async/await` are not the same at all.
Svelte does not have a `createResource` alternative. `createResource` is doing exactly what we are doing manually in Svelte and other framework providing `loading`, `error`, `result` reactive data.

**Comment by jinyus** [comment]
Doesn't svelte's `await` block provide `loading`, `error`, `result` states just like in solid? Solid allows you do retries etc. but in this case, it's functioning just like the `await` block. 

Since we shouldn't use svelte's `await` block, shouldn't we also not use Solid's `createResource` and make it look like the other frameworks?

**Pull request closed without merging**
